site_name: 正座のCodesys

theme:
  name: material
  palette:
    primary: blue
  font:
    text: UD Digi Kyokasho NK-R
  features:
    navigation.prune: true
    navigation.tabs: true
    navigation.top: true

markdown_extensions:
  - admonition

nav:
  - Home:
      - "Index": index.md
      - "Introduction": Others/Introduction.md
  - Codesys:
      - "デバッグ機能": Codesys/Debug.md
  - IEC:
      - "基本機能":
          - "Function": IEC/Function.md
          - "Function Block": IEC/Function_Block.md
          - "STRING/WSTRING 関数": IEC/STRING_WSTRING_Function.md
